# DAOS Agent configuration file

name: daos_server
hostlist: ['daos-server']
port: 10001

#runtime_dir: /var/run/daos_agent
#log_file: /tmp/daos_agent.log
#control_log_mask: info

transport_config:
  allow_insecure: true

